kind: ConfigMap
apiVersion: v1
metadata:
  name: request-handler
data:
  application.yml: |-
    server:
      port: 8989
    logging:
      level:
        org.springframework.security: TRACE
        org.springframework.cloud.gateway: TRACE
        com.felips: TRACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-handler
  labels:
    app: request-handler
spec:
  selector:
    matchLabels:
      app: request-handler
  template:
    metadata:
      labels:
        app: request-handler
    spec:
      containers:
      - name: request-handler
        image: request-handler
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: request-handler
spec:
  type: NodePort
  selector:
    app: request-handler
  ports:
    - port: 8989
      targetPort: 8989
      nodePort: 32200
